### ISSUE TITLE
Obscure behavior when text is longer then grammar can consume

### ISSUE THREAD

**Issue by amerlyq** [igordejanovic/parglare#16] opened 2017-11-16 12:57 UTC
* parglare version: 0.5.dev0
* Python version: 3.6.3
* Operating System: ArchLinux 4.13.11

### Description

I tried to split text into paragraphs, keeping whitespaces as significant terms.
As first step of deriving grammar, I tried to parse two separate lines instead of paragraphs. 
But when using knowingly wrong grammar, which can parse only first line -- I expected error.
Instead of error, `parglare` simply parsed first line and dropped the rest of text.
Is it intentional behavior? 

### What I Did

```python
g = Grammar.from_string('T: NL* L+ NL* | NL*; L: /.+/; NL: "\n";', re_flags=re.MULTILINE)
print(Parser(g, ws=False).parse('\nL1\nL2\n\n'))
# [['\n'], ['L1'], ['\n']]
```
I expected parse error, e.g. "expected STOP but received L2".

**Comment by igordejanovic** [comment] 2017-11-22 08:31
Yes, it is intended behaviour although not yet documented as it seems. 

parglare will not assume by default that the whole input should be consumed. If you want to do that use `EOF` rule at the end:
```
g = Grammar.from_string('S: T EOF; T: NL* L+ NL* | NL*; L: /.+/; NL: "\n";', re_flags=re.MULTILINE)
```
I'll close this issue when the docs get fixed.

**Comment by igordejanovic** [comment] 2018-02-09 08:43
Documented [here](http://www.igordejanovic.net/parglare/grammar_language/#special-built-in-rules)

**Closed by igordejanovic** 2018-02-09 08:43 UTC
Labels: docs needed

**Comment by amerlyq** [comment] 2018-10-21 17:15
By the way, your solution above results into irritating `None` at the end of the ast with one more nesting level, i.e.:
```python
g = Grammar.from_string('S: T EOF; T: NL* L+[NL] NL* | NL*; terminals L: /.+/; NL: "\n";', re_flags=re.MULTILINE)
print(Parser(g, ws=False).parse('\nL1\nL2\n\n'))
# [[['\n'], ['L1', 'L2'], ['\n', '\n']], None]

g = Grammar.from_string('S: L* EOF; terminals L: /.*/;')
print(Parser(g).parse('\nL1\nL2\n\n'))
# [['L1', 'L2'], None]
```
Is it intended? How to rid of that `None`? Or is it has some useful purpose?

**Comment by igordejanovic** [comment] 2018-10-21 18:54
Each rule, when reduced, will either call registered action or the default action. The default action for non-terminals is to create a list of elements where each element correspond to RHS element. I decided not to introduce any implicit removal, for the user to be sure how many elements will be in the list, so `EOF` also produces a result which is `None`. If you are using the default action, like in the example above, be sure to unpack your result:
```python
result, _ = Parser(g).parse('...')
```
or
```python
result = Parser(g).parse('...')[:-1]
```
If you prefer to get a clean result from the parse call than register your [actions](http://www.igordejanovic.net/parglare/latest/actions/), at least for the root rule.
There is a built-in action `pass_single` which will work nice in your example:
```python
g = Grammar.from_string('@pass_single S: L* EOF; terminals L: /.*/;')
print(Parser(g).parse('\nL1\nL2\n\n'))
# ['L1', 'L2']
```

**Comment by igordejanovic** [comment] 2018-10-21 19:04
As a side note, I think that a special built-in actions `strip_first` and `strip_last` could be added as that feels to be a frequent requirement. In that case `strip_last` would be a more general approach as it would work in the case when you have more than one rule before `EOF`. I'm registering issue #63 for tracking this.

**Comment by amerlyq** [comment] 2018-10-21 20:44
By the way, I found only now, but the very first example which started this whole issue works as I had expected at the very beginning, i.e. parses till the very end. Isn't it regression comparing to what you described earlier and in the current docs? 
http://www.igordejanovic.net/parglare/stable/grammar_language/#special-built-in-rules
I expected that same snippet will continue to work same way, but now it produces error as I wanted...
```
g = Grammar.from_string('T: NL* L+ NL* | NL*; L: /.+/; NL: "\n";', re_flags=re.MULTILINE)
print(Parser(g, ws=False).parse('\nL1\nL2\n\n'))
# ParseError: Error at 3:0:"\nL1\n*L2\n\n" => Expected: STOP but found <L(L2)>
```

**Comment by igordejanovic** [comment] 2018-10-22 06:29
Seems that your are right. It looks like a regression. The old behavior should be the correct one. Will investigate.

Yes, actions are not affecting parsing in any way, they are affecting just the resulting output. In the future there might be a support for side-effects and interplay between actions, recognizers and dynamic disambiguation which will bring a possibility to affect the parsing course from different parts of user written code.
